language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

script: |
  vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  source autoload/replace.vim
  filetype plugin indent on
  VIMRC) -c 'Vader! test/*' > /dev/null

notifications:
  email: false
